# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rajatdixit.github.io/
baseurl: /sustain/
title: Rajat Dixit
author: Rajat Dixit
description: Portfolio
avatar: profile.png
email: contact@rajatdixit.ca
github: rajatdixit/resume # username
#twitter: username
linkedin: dixitrajat
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
